sensor:
  title: Sensor
  type: object
  description: Sensor's description and physical variables
  properties:
    id:
      description: Sensor identifier
      type: string
      format: uri
      example: urn:ngsi-ld:Sensor:[uuid]
      x-ngsi:
        type: Property    
    energyConsumption:
      description: Electrical energy consumed by a given asset/kWh
      minimum: 0
      type: number
      x-ngsi:
        uri: "https://projetobioma.pt/dataModel/energyConsumption"
        uri-prefix: "https://projetobioma.pt/dataModel/"
        type: Property
        units: KWH
    waterConsumption:
      description: Water consumption by a given asset within a process (e.g. machine, irrigation line, etc.)/m3
      minimum: 0
      type: number
      x-ngsi:
        uri: "https://projetobioma.pt/dataModel/waterConsumption"
        uri-prefix: "https://projetobioma.pt/dataModel/"
        type: Property
        units: MTQ
  required:
    - id